core/urls.py
from django.conf.urls import patterns, url
from core import views
from workspace import views as wp_views


urlpatterns = patterns('',
    url(r'^$', views.index,  name='index'),
    #user actions
    url(r'^user-registration/$', views.user_register,  name='user_registration'),
    url(r'^partner/registration/$', views.partner_register,  name='registration'),
    url(r'^account/login/$',   views.user_login,  name='user_login'),
    url(r'^partner/profile/update/$',   views.profile_update,  name='profile_update'),
    url(r'^partner/profile/$',   views.profile_info,  name='profile_info'),
    url(r'^account/logout/$',   views.user_logout,  name='user_logout'),
    url(r'^account/password/change/$',   views.userPasswordChange,  name='password_change'),

    url(r'^user/application-page/message/$',views.message_form,name='message_form'),

    url(r'^user/application-page/(?P<id>.*?)/$',views.ApplicationPageView.as_view(),name='application_page'),

    url(r'^user/$',views.user_profile,name='user_profile'),


    url(r'^confirm/(?P<activation_key>[-\w]+)/$',   views.user_confirm,  name='user_confirm'),

    #partnership panel
    url(r'^ppanel/$',  wp_views.partnership_panel,  name='partnership_panel'),
    url(r'^ppanel/employee/(?P<id>[-\w]+)/$',  wp_views.employee_info,  name='employee_info'),
    url(r'^ppanel/workspace/view/(?P<id>.*?)/$',  wp_views.workspace_detail,  name='workspace_detail'),
)

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings

from . import views
from news.settings import ARCHIVE_PAGE_SIZE




urlpatterns = patterns('django.views.generic.date_based',
    url(r'^$', #paginate_by must be egual 
        views.ArchiveIndexView.as_view(paginate_by=ARCHIVE_PAGE_SIZE), name='news_archive_index'),

    url(r'^(?P<slug>[-\w]+)/$',
        views.DetailView.as_view(), name='news_detail'),

)

universus_partnership/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns



admin.autodiscover() 
urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^partnership-program/', include('partnership_program.urls', namespace='partnership_program')),
    url(r'^vacancy/', include('vacancy.urls', namespace='vacancy')),

    url(r'^', include('core.urls', namespace='core')),
)

# ... the rest of your URLconf goes here ...

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

core/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from core.models import User, Partner, PartnerCategory
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth import authenticate, login, logout

from django import forms
from django.forms import ModelForm

class CustomUserCreationForm(UserCreationForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """

    def __init__(self, *args, **kargs):
        super(CustomUserCreationForm, self).__init__(*args, **kargs)
        del self.fields['username']

    class Meta:
        model = User
        fields = ("email",)

class CustomUserChangeForm(UserChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    def __init__(self, *args, **kargs):
        super(CustomUserChangeForm, self).__init__(*args, **kargs)
        del self.fields['username']

    class Meta:
        model = User


#user register. added by mubariz
class UserRegisterForm(ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, label=_('Password'), max_length=50)
    password2 = forms.CharField(widget=forms.PasswordInput, label=_('Confirm Password'), max_length=50)
    class Meta:
        model = User
        fields = ['email','password1', 'password2', 'first_name', 'last_name', 'phone',
                  'country','city','skype',]

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data.get("password2", "")
        if password1 and password2:  # If both passwords has value
            if password1 != password2:
                raise forms.ValidationError(_(u"Passwords didn't match."))
        else:
            raise forms.ValidationError(_(u"Passwords can't be blank."))
        return password2


#partner register
class RegisterForm(ModelForm):
    first_name = forms.CharField(label=_('First Name'), max_length=50)
    last_name = forms.CharField(label=_('Last Name'), max_length=50)
    user_email = forms.EmailField(label=_('Your Email'))
    user_phone = forms.CharField(label=_('Your Phone'), max_length=50, required=False)
    user_position = forms.CharField(label=_('Your Position'), max_length=50, required=False)
    password1 = forms.CharField(widget=forms.PasswordInput, label=_('Password'), max_length=50)
    password2 = forms.CharField(widget=forms.PasswordInput, label=_('Confirm Password'), max_length=50)


    class Meta:
        model = Partner
        fields = ['user_email','password1', 'password2', 'first_name', 'last_name', 'user_phone',
                  'country', 'city', 'company', 'address', 'zipcode', 'partner_email', 'phone', 'skype', 'website', 'fax', 'logo']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data.get("password2", "")
        if password1 and password2:  # If both passwords has value
            if password1 != password2:
                raise forms.ValidationError(_(u"Passwords didn't match."))
        else:
            raise forms.ValidationError(_(u"Passwords can't be blank."))
        return password2

    def clean_user_email(self):
        user_email = self.cleaned_data.get("user_email", "")
        user = User.objects.filter(email=user_email)
        if user:
            raise forms.ValidationError(_(u"User with this email already exist."))
        return user_email


class UpdatePartnerForm(ModelForm):
    class Meta:
        model = Partner
        fields = ['country', 'city', 'company', 'address', 'zipcode', 'partner_email', 'phone','skype','website','fax','logo']


class UpdateUserForm(ModelForm):
    user_phone = forms.CharField(label=_('Your Phone'), required=False, max_length=50)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'user_phone', 'position']

class LoginForm(forms.Form):
    username = forms.EmailField(label=_('Username'))
    password = forms.CharField(widget=forms.PasswordInput,
                                label=_('Password'),
                                max_length=50)


    class Meta:
        fields = ['username','password']

    def clean_password(self):
        username = self.cleaned_data.get("username", "")
        password = self.cleaned_data.get("password", "")
        user = authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError(_(u"Username or Passwords is not valid."))
        elif not user.is_active:
            raise forms.ValidationError(_(u"This user is not active"))
        return password


#This form is used for change password current user.
class PasswordChangeForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput,
                                label=_('Current Password'),
                                max_length=50, required=True)
    password1 = forms.CharField(widget=forms.PasswordInput,
                                label=_('New Password'),
                                max_length=50, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label=_('Confirm Password'),
                                max_length=50, required=True)


    class Meta:
        fields = ['password','password1', 'password2']

    def __init__(self, user, data=None, *args, **kwargs):
        self.user = user
        self.data = data
        super(PasswordChangeForm, self).__init__(data=data, *args, **kwargs)

    #validating old password.
    def clean_password(self):
        password = self.cleaned_data.get('password', None)
        if not self.user.check_password(password):
            raise forms.ValidationError(_('Current password is wrong.'))
        return password

    #checking both password exist and same.
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data.get("password2", "")
        if password1 and password2:  # If both passwords has value
            if password1 != password2:
                raise forms.ValidationError(_(u"Passwords didn't match."))
        else:
            raise forms.ValidationError(_(u"Passwords can't be blank."))
        return password2

templates/partner/change_password.html
{% extends "base.html" %}
{% load i18n %}

<title>{% block title %}{% trans 'Pasword Changing' %}{% endblock %}</title>

{% block content %}

    <h1> {% trans 'Change Password' %}</h1>
    <div class="ui form segment">
        <form action="{% url 'core:password_change'  %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div {% if field.errors %} class="field error" {% else %} class="field" {% endif %}>
                  {{ field.label_tag }}
                  {{ field }}
                  {% if field.errors %}
                        <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                            {{ field.errors.0 }}
                        </div>
                  {% endif %}
                </div>
            {% endfor %}

            <button class="ui blue button right">{% trans 'Change Password' %}</button>

        </form>
   </div>

{% endblock %}

templates/partner/employee_register.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} {% trans 'Adding employee' %} {% endblock %}
{% block content %}

   <h1>{% trans 'Adding employee' %}</h1>

    <div>
        <p>{% trans 'Activation link is sent your email address. Please confirm account of your user for activation' %}</p>
    </div>


{% endblock %}

templates/partner/login.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {% trans 'Log in Partnership Portal' %} {% endblock %}
}
{% block content %}
    <h1>{% trans 'Log in Partnership Portal' %}</h1>
    <div class="ui two column middle aligned relaxed grid basic segment">
        <div class="column">
            <div class="ui form segment">
                <form action="{% url 'core:user_login' %}" method="post">
                    {% csrf_token %}
                    {% if req_url %}
                        <input type="hidden" name="next" value="{{ req_url }}" />
                    {% endif %}

                    <div {% if form.username.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.username.label_tag }}
                          <div class="ui left labeled icon input">
                              {{ form.username }}
                              <i class="user icon"></i>
                                  <div class="ui corner label">
                                    <i class="asterisk icon"></i>
                                  </div>
                          </div>
                          {% if form.username.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block; width:295px;">
                                    {{ form.username.errors.0 }}
                                </div>
                          {% endif %}
                    </div>
                    <div {% if form.password.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.password.label_tag }}
                          <div class="ui left labeled icon input">
                              {{ form.password }}
                              <i class="lock icon"></i>
                                  <div class="ui corner label">
                                    <i class="asterisk icon"></i>
                                  </div>
                          </div>
                          {% if form.password.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;width:295px;">
                                    {{ form.password.errors.0 }}
                                </div>
                          {% endif %}
                    </div>
                    <button style="margin-top: 8px;" class="ui blue submit button">{% trans 'Log in' %}</button>
                </form>
            </div>
        </div>
        <div class="ui vertical divider">
            {% trans 'Or' %}
        </div>
        <div class="center aligned column">
            <a href="{% url 'core:registration' %}">
                <div class=" green ui labeled icon button">
                    <i class="signup icon"></i>
                    {% trans 'Sign Up  as Partner' %}
                </div>
            </a>

{#        </div>#}
{#        <div class="center aligned column">#}

            <a href="{% url 'core:user_registration' %}">
                <br>
                <div class=" green ui labeled icon button">
                    <i class="signup icon"></i>
                    {% trans 'Sign Up as User' %}
                </div>
            </a>
        </div>
    </div>



	
{% endblock %}

templates/partner/partnership_panel.html
{% extends 'base.html' %}
{% load i18n core_tags %}
{% block title %} {% trans 'Partnership Panel' %} {% endblock %}

{% block head.extra %}
    <script>
        function showWSForm(element) {
            $("#add_ws_block").show();
            $("#show_add_new_ws").hide();
        }
    </script>

    <script>
        function showUserForm(element) {
            $("#add_user_block").show();
            $("#show_add_new_user").hide();
        }
    </script>

{% endblock head.extra %}

{% block content %}
    <h1>{% trans 'Partnership panel' %}</h1>
    {% if is_partner %}
        <div class="ppanel">
            <h3><i class="archive icon" ></i>{% trans 'Workspaces' %}</h3>
            <table class="ui large table segment">
                <thead>
                    <tr><th>{% trans 'Subject' %}</th>
                    <th>{% trans 'Files' %}</th>
                    <th>{% trans 'Messages' %}</th>
                    <th>{% trans 'Created date' %}</th>
                  </tr>
                </thead>
                <tbody>
                {% for workspace in workspaces %}
                    <tr >
                        <td><a href="{%  url 'core:workspace_detail' workspace.id %}">{{ workspace.name }}</a></td>
                        <td>{{ workspace.files.all|length }} {% trans ' files' %}</td>
                        <td><i class="mail icon" ></i>{{ workspace.messages.all|length }} {% trans ' messages' %}</td>
                        <td>{{ workspace.created_date|date:'b d, Y H:i'  }}</td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                    {% if user.manager %}
                        <tr><th colspan="4">
                          <button id="show_add_new_ws" onclick="showWSForm(this)" style="padding-top: 5px; padding-bottom: 5px;" class="ui blue right labeled icon button">
                                <i style="padding-top: 5px;" class="add sign box icon"></i>
                                {% trans 'add new' %}
                            </button>
                            </th>
                        </tr>
                    {% endif %}
                </tfoot>
            </table>

            <div id="add_ws_block" {% if not workspace_form.errors %} hidden="" {% endif %} class="ui form segment">
                <form id="add_ws_form" action="{%  url 'core:partnership_panel' %}" method="post">
                    {% csrf_token %}
                    <div {% if workspace_form.name.errors %} class="field error" {% else %} class="field" {% endif %}>
                        {{ workspace_form.name.label_tag }}
                        {{ workspace_form.name }}
                        {% if workspace_form.name.errors %}
                            <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                {{ workspace_form.name.errors.0 }}
                            </div>
                        {% endif %}
                    </div>

                    <div style="margin-bottom: 5px;" class="field" >
                        {{ workspace_form.description.label_tag }}
                        {{ workspace_form.description }}
                    </div>

                    <button  style="padding-top: 5px; padding-bottom: 5px;" class="ui blue right labeled icon button">
                        <i style="padding-top: 5px;" class="add sign box icon"></i>
                        {% trans 'create' %}
                    </button>
                </form>
            </div>

            <br/>

            <h3 class="partnership-programs">{% trans 'Partnership programs' %}</h3>
            <table class="ui large table segment">
                <thead>
                    <tr><th>{% trans 'Program' %}</th>
                    <th>{% trans 'Status' %}</th>
                    <th>{% trans 'Update date' %}</th>
                  </tr>
                </thead>
                <tbody>
                {% for program in programs %}
                    {% with status=program|get_program_status:user.partner %}
                        {% if status != 'None' %}
                        <tr >
                            <td>{{ program.name }}</td>
                            <td>{{ status }}</td>
                            <td>{{ program.update_date }}</td>
                        </tr>
                        {% endif %}
                    {% endwith %}
                {% endfor %}
                </tbody>
            </table>

            <br/>

            <h3><i class="community basic icon" ></i>{% trans 'Your employees' %}</h3>
            <table class="ui large table segment">
                <thead>
                    <tr><th>{% trans 'Name' %}</th>
                    <th>{% trans 'Position' %}</th>
                  </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr >
                        <td><a href="{% url 'core:employee_info' user.id %}">{{ user.get_full_name }}</a></td>
                        <td> {{ user.position }}</td>
                    </tr>
                {% endfor %}
                </tbody>
              <tfoot>
                <tr><th colspan="3">
                    {% if user.manager %}
                    <button id="show_add_new_user" onclick="showUserForm(this)" style="padding-top: 5px; padding-bottom: 5px;" class="ui blue right labeled icon button">
                        <i style="padding-top: 5px;" class="add sign box icon"></i>
                        {% trans 'add new' %}
                    </button>
                    {% endif %}
                </th>
              </tr></tfoot>
            </table>

            <div id="add_user_block" {% if not user_form.errors %} hidden="" {% endif %} class="ui form segment">
                <div class="ui form segment">
                    <form action="{% url 'core:partnership_panel'  %}" method="post">
                        {% csrf_token %}

                        <div class="two fields">
                          <div {% if user_form.first_name.errors %} class="field error" {% else %} class="field" {% endif %}>
                            {{ user_form.first_name.label_tag }}
                            <input id="id_first_name" maxlength="50" placeholder="{% trans 'First Name' %}" name="first_name" type="text" />
                            {% if user_form.first_name.errors %}<div class="ui red pointing prompt label transition visible" style="display: inline-block;">{{ user_form.first_name.errors.0 }}</div>{% endif %}
                          </div>

                          <div {% if user_form.last_name.errors %} class="field error" {% else %} class="field" {% endif %}>
                            {{ user_form.last_name.label_tag }}
                            <input id="id_last_name" maxlength="50" placeholder="{% trans 'Last Name' %}" name="last_name" type="text" />
                            {% if user_form.last_name.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ user_form.last_name.errors.0 }}
                                </div>
                            {% endif %}
                          </div>
                        </div>

                        <div {% if user_form.email.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ user_form.email.label_tag }}
                          {{ user_form.email }}
                          {% if user_form.email.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ user_form.email.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                        <div {% if user_form.password1.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ user_form.password1.label_tag }}
                          {{ user_form.password1 }}
                          {% if user_form.password1.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ user_form.password1.errors.0 }}
                                </div>
                          {% endif %}
                        </div>
                        <div {% if user_form.password2.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ user_form.password2.label_tag }}
                          {{ user_form.password2 }}
                          {% if user_form.password2.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ user_form.password2.errors.0 }}
                                </div>
                          {% endif %}
                        </div>

                        <div {% if user_form.position.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ user_form.position.label_tag }}
                          {{ user_form.position }}
                          {% if user_form.position.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ user_form.position.errors.0 }}
                                </div>
                          {% endif %}
                        </div>

                        <div {% if user_form.company.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ user_form.company.label_tag }}
                          {{ user_form.company }}
                          {% if user_form.company.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ user_form.company.errors.0 }}
                                </div>
                          {% endif %}
                        </div>


                        <div class="two fields">
                          <div class="field">
                            {{ user_form.country.label_tag }}
                            {{ user_form.country }}
                          </div>

                          <div class="field">
                            {{ user_form.city.label_tag }}
                            {{ user_form.city }}
                          </div>
                        </div>

                        <div class="two fields">
                          <div class="field">
                            {{ user_form.phone.label_tag }}
                            {{ user_form.phone }}
                          </div>
                          <div class="field">
                            {{ user_form.skype.label_tag }}
                            {{ user_form.skype }}
                          </div>
                        </div>
                        <button class="ui blue button right">{% trans 'create' %}</button>

                    </form>
                </div>
            </div>

        </div>
    {% else %}
        {% trans 'Acess denied.' %}
    {% endif %}


{% endblock content %}

templates/partner/user_register.html
{% extends "base.html" %}
{% load i18n %}

<title>{% block title %} {% trans 'User Registration' %} {% endblock %}</title>

{% block content %}

{#   {% if message_sent %}#}
    <p>
{#        {% trans '' %}#}
{#    {% else %}#}
       <h1>{% trans 'User Registration' %}</h1>
       <div class="ui form segment">
            <form autocomplete="off" action="{% url 'core:user_registration'  %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                        <div class="two fields">
                          <div {% if form.first_name.errors %} class="field error" {% else %} class="field" {% endif %}>
                            {{ form.first_name.label_tag }}
                            <input id="id_first_name" maxlength="50" placeholder="{% trans 'First Name' %}" name="first_name" type="text" />
                            {% if form.first_name.errors %}<div class="ui red pointing prompt label transition visible" style="display: inline-block;">{{ form.first_name.errors.0 }}</div>{% endif %}
                          </div>

                          <div {% if form.last_name.errors %} class="field error" {% else %} class="field" {% endif %}>
                            {{ form.last_name.label_tag }}
                            <input id="id_last_name" maxlength="50" placeholder="{% trans 'Last Name' %}" name="last_name" type="text" />
                            {% if form.last_name.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.last_name.errors.0 }}
                                </div>
                            {% endif %}
                          </div>
                        </div>

                        <div {% if form.email.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.email.label_tag }}
                          {{ form.email }}
                          {% if form.email.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.email.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                        <div {% if form.password1.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.password1.label_tag }}
                          {{ form.password1 }}
                          {% if form.password1.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.password1.errors.0 }}
                                </div>
                          {% endif %}
                        </div>
                        <div {% if form.password2.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.password2.label_tag }}
                          {{ form.password2 }}
                          {% if form.password2.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.password2.errors.0 }}
                                </div>
                          {% endif %}
                        </div>

                        <div {% if form.phone.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.phone.label_tag }}
                          {{ form.phone }}
                          {% if form.phone.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.phone.errors.0 }}
                                </div>
                          {% endif %}
                        </div>


                        <div class="two fields">
                          <div class="field">
                            {{ form.country.label_tag }}
                            {{ form.country }}
                          </div>

                          <div class="field">
                            {{ form.city.label_tag }}
                            {{ form.city }}
                          </div>
                        </div>

                        <div class="two fields">
                          <div class="field">
                            {{ form.skype.label_tag }}
                            {{ form.skype }}
                          </div>
                        </div>
                        <button class="ui blue button">{% trans 'Submit' %}</button>

            </form>
       </div>
                

{#    {% endif %}#}

	
{% endblock %}