core/urls.py
from django.conf.urls import patterns, url
from core import views
from workspace import views as wp_views


urlpatterns = patterns('',
    url(r'^$', views.index,  name='index'),
    #user actions
    url(r'^user-registration/$', views.user_register,  name='user_registration'),
    url(r'^partner/registration/$', views.partner_register,  name='registration'),
    url(r'^account/login/$',   views.user_login,  name='user_login'),
    url(r'^partner/profile/update/$',   views.profile_update,  name='profile_update'),
    url(r'^partner/profile/$',   views.profile_info,  name='profile_info'),
    url(r'^account/logout/$',   views.user_logout,  name='user_logout'),
    url(r'^account/password/change/$',   views.userPasswordChange,  name='password_change'),

    url(r'^user/application-page/message/$',views.message_form,name='message_form'),

    url(r'^user/application-page/(?P<id>.*?)/$',views.ApplicationPageView.as_view(),name='application_page'),

    url(r'^user/$',views.user_profile,name='user_profile'),


    url(r'^confirm/(?P<activation_key>[-\w]+)/$',   views.user_confirm,  name='user_confirm'),

    #partnership panel
    url(r'^ppanel/$',  wp_views.partnership_panel,  name='partnership_panel'),
    url(r'^ppanel/employee/(?P<id>[-\w]+)/$',  wp_views.employee_info,  name='employee_info'),
    url(r'^ppanel/workspace/view/(?P<id>.*?)/$',  wp_views.workspace_detail,  name='workspace_detail'),
)

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings

from . import views
from news.settings import ARCHIVE_PAGE_SIZE




urlpatterns = patterns('django.views.generic.date_based',
    url(r'^$', #paginate_by must be egual 
        views.ArchiveIndexView.as_view(paginate_by=ARCHIVE_PAGE_SIZE), name='news_archive_index'),

    url(r'^(?P<slug>[-\w]+)/$',
        views.DetailView.as_view(), name='news_detail'),

)

universus_partnership/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns



admin.autodiscover() 
urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^partnership-program/', include('partnership_program.urls', namespace='partnership_program')),
    url(r'^vacancy/', include('vacancy.urls', namespace='vacancy')),

    url(r'^', include('core.urls', namespace='core')),
)

# ... the rest of your URLconf goes here ...

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

vacancy/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
# from django.conf import settings
from . import models
from . import views

urlpatterns = patterns('django.views.generic.date_based',

        url(r'^(?P<slug>.*?)/$',views.VacancyDetailView.as_view(), name='vacancy_detail'),

        url(r'^$',views.vacancy_list, name='vacancy_list'),

)

vacancy/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
import functools
from modeltranslation.translator import translator, TranslationOptions
from ckeditor.fields import RichTextField
from core.models import User
import datetime
import os.path

# Create your models here.


class Vacancy(models.Model):
    name = models.CharField(_('Vacancy Name'),max_length=255)
    slug = models.CharField(_('Slug'),max_length=255)
    location =models.CharField(_('Location'),max_length=255)
    salary_description = models.CharField(_('Salary Description'),max_length=255)
    education = models.CharField(_('Education'),max_length=255)
    experience = models.CharField(_('Experience'),max_length=255)
    job_description = models.TextField(_('Job Description'),max_length=255)

    def __unicode__(self):
        return self.name

class ApplicationStatus(models.Model):
    name = models.CharField(_('Name'),max_length=255)
    code = models.CharField(_('Code'),max_length=40)
    def __unicode__(self):
        return self.name

class VacancyApplication(models.Model):
    vacancy = models.ForeignKey(Vacancy)
    userid = models.ForeignKey(User)
    cv = models.FileField(_('CV'),upload_to = 'vacancy/cv/')
    message = models.CharField(_('Message'),max_length=255)

    senddate = models.DateTimeField(_('Send Date'),auto_now_add=True)
    status = models.ForeignKey(ApplicationStatus)

    def __unicode__(self):
        return self.vacancy

class ApplicationTask(models.Model):
    applicationid = models.ForeignKey(VacancyApplication, related_name='tasks')
    name = models.CharField(_('Name'),max_length=255)
    sourcefile = models.FileField(_("SourceFile"),upload_to = 'vacancy/sourcfile/', blank=True)
    deadline = models.DateTimeField(_('Deadline'))
    resultdate = models.DateTimeField(_('ResultDate'))
    resultfile = models.FileField(_('ResultFile'),upload_to = 'vacancy/resultfile/', blank=True)

    def __unicode__(self):
        return self.name
    # def sourcefilename(self):
    #     return os.path.basename(self.sourcefile.name)
    # def resultfilename(self):
    #     return os.path.basename(self.resultfile.name)

class ApplicationInterview(models.Model):
    applicationid = models.ForeignKey(VacancyApplication)
    date = models.DateTimeField(_('Date'))
    connection = models.CharField(_('Connection'),max_length=255)
    comment = models.CharField(_('Comment'),max_length=255)

    # def __unicode__(self):
    #     return self.applicationid

class JobApplicationMessage(models.Model):
    userid=models.ForeignKey(User, blank=True, null=True)
    applicationid = models.ForeignKey(VacancyApplication)
    senddate =models.DateTimeField(_('Send Date'),auto_now_add=True)
    message = models.TextField(_('Message'))

    class Meta:
        verbose_name = _('Application Message')
        verbose_name_plural = _('Application Messages')
        ordering = ('-senddate', )

    def __unicode__(self):
        return self.message





core/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from core.models import User, Partner, PartnerCategory
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth import authenticate, login, logout

from django import forms
from django.forms import ModelForm

class CustomUserCreationForm(UserCreationForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """

    def __init__(self, *args, **kargs):
        super(CustomUserCreationForm, self).__init__(*args, **kargs)
        del self.fields['username']

    class Meta:
        model = User
        fields = ("email",)

class CustomUserChangeForm(UserChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    def __init__(self, *args, **kargs):
        super(CustomUserChangeForm, self).__init__(*args, **kargs)
        del self.fields['username']

    class Meta:
        model = User


#user register. added by mubariz
class UserRegisterForm(ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, label=_('Password'), max_length=50)
    password2 = forms.CharField(widget=forms.PasswordInput, label=_('Confirm Password'), max_length=50)
    class Meta:
        model = User
        fields = ['email','password1', 'password2', 'first_name', 'last_name', 'phone',
                  'country','city','skype',]

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data.get("password2", "")
        if password1 and password2:  # If both passwords has value
            if password1 != password2:
                raise forms.ValidationError(_(u"Passwords didn't match."))
        else:
            raise forms.ValidationError(_(u"Passwords can't be blank."))
        return password2


#partner register
class RegisterForm(ModelForm):
    first_name = forms.CharField(label=_('First Name'), max_length=50)
    last_name = forms.CharField(label=_('Last Name'), max_length=50)
    user_email = forms.EmailField(label=_('Your Email'))
    user_phone = forms.CharField(label=_('Your Phone'), max_length=50, required=False)
    user_position = forms.CharField(label=_('Your Position'), max_length=50, required=False)
    password1 = forms.CharField(widget=forms.PasswordInput, label=_('Password'), max_length=50)
    password2 = forms.CharField(widget=forms.PasswordInput, label=_('Confirm Password'), max_length=50)


    class Meta:
        model = Partner
        fields = ['user_email','password1', 'password2', 'first_name', 'last_name', 'user_phone',
                  'country', 'city', 'company', 'address', 'zipcode', 'partner_email', 'phone', 'skype', 'website', 'fax', 'logo']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data.get("password2", "")
        if password1 and password2:  # If both passwords has value
            if password1 != password2:
                raise forms.ValidationError(_(u"Passwords didn't match."))
        else:
            raise forms.ValidationError(_(u"Passwords can't be blank."))
        return password2

    def clean_user_email(self):
        user_email = self.cleaned_data.get("user_email", "")
        user = User.objects.filter(email=user_email)
        if user:
            raise forms.ValidationError(_(u"User with this email already exist."))
        return user_email


class UpdatePartnerForm(ModelForm):
    class Meta:
        model = Partner
        fields = ['country', 'city', 'company', 'address', 'zipcode', 'partner_email', 'phone','skype','website','fax','logo']


class UpdateUserForm(ModelForm):
    user_phone = forms.CharField(label=_('Your Phone'), required=False, max_length=50)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'user_phone', 'position']

class LoginForm(forms.Form):
    username = forms.EmailField(label=_('Username'))
    password = forms.CharField(widget=forms.PasswordInput,
                                label=_('Password'),
                                max_length=50)


    class Meta:
        fields = ['username','password']

    def clean_password(self):
        username = self.cleaned_data.get("username", "")
        password = self.cleaned_data.get("password", "")
        user = authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError(_(u"Username or Passwords is not valid."))
        elif not user.is_active:
            raise forms.ValidationError(_(u"This user is not active"))
        return password


#This form is used for change password current user.
class PasswordChangeForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput,
                                label=_('Current Password'),
                                max_length=50, required=True)
    password1 = forms.CharField(widget=forms.PasswordInput,
                                label=_('New Password'),
                                max_length=50, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label=_('Confirm Password'),
                                max_length=50, required=True)


    class Meta:
        fields = ['password','password1', 'password2']

    def __init__(self, user, data=None, *args, **kwargs):
        self.user = user
        self.data = data
        super(PasswordChangeForm, self).__init__(data=data, *args, **kwargs)

    #validating old password.
    def clean_password(self):
        password = self.cleaned_data.get('password', None)
        if not self.user.check_password(password):
            raise forms.ValidationError(_('Current password is wrong.'))
        return password

    #checking both password exist and same.
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data.get("password2", "")
        if password1 and password2:  # If both passwords has value
            if password1 != password2:
                raise forms.ValidationError(_(u"Passwords didn't match."))
        else:
            raise forms.ValidationError(_(u"Passwords can't be blank."))
        return password2

vacancy/views.py
from django.views import generic as generic_views
# from django.views import FormMixin, ListView
# from . import models,settings
# from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.template import RequestContext

from django.shortcuts import render,render_to_response
from django.http import HttpResponse
from django.shortcuts import render
# Create your views here.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~BOOK CATEGORY LIST~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from django.http import HttpResponseRedirect,Http404
# from .forms import UploadFileForm
from django.utils import translation
from models import Vacancy,VacancyApplication
from forms import VacancyApplicationForm
from django.utils import timezone
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.core.context_processors import csrf
from django.core.mail import send_mail, BadHeaderError
# from universus_public.settings import EMAIL_HOST_USER
from django.db.models import Q
# Create your views here.
from core.models import User
from django.views.generic.edit import FormMixin
from django.views.generic.list import ListView

def vacancy_list(request):
    template_name = 'vacancy/vacancy_list.html'
    cur_language=request.LANGUAGE_CODE
    vacancy_list = Vacancy.objects.all()
    default_url=1


    return render(request,'vacancy/vacancy_list.html',{'cur_language':cur_language,'vacancy_list':vacancy_list,'default_url':default_url})

class VacancyDetailView(FormMixin, ListView):
    model = Vacancy
    template_name = 'vacancy/vacancy_detail.html'
    form_class = VacancyApplicationForm
    success_url = '/thanks/'

    def get(self, request, *args, **kwargs):
     # From ProcessFormMixin
        form_class = self.get_form_class()
        self.form = self.get_form(form_class)

        if self.request.method == 'POST':
            # return HttpResponse(self.form.errors)
            self.form_class(request.POST, request.FILES)
            if self.form.is_valid():
                obj = self.form.save(commit=False)
                # obj.save()
#             return HttpResponseRedirect('/thanks/')
        else:
            self.form_class(self.request.POST,request.FILES)

            # return super(ProductListView, self).form_valid(form)

        # From BaseListView
        self.object_list = self.get_queryset()
        # allow_empty = self.get_allow_empty()
        # if not allow_empty and len(self.object_list) == 0:
        #     raise Http404(_(u"Empty list and '%(class_name)s.allow_empty' is False.")
        #                   % {'class_name': self.__class__.__name__})

        context = self.get_context_data(object_list=self.object_list, form=self.form)
        # context = super(VacancyDetailView, self).get_context_data(**kwargs)
        context['slug'] = Vacancy.objects.all()
        vacancy_obj = Vacancy.objects.get(slug=self.kwargs['slug'])
        context['vacancy'] = vacancy_obj
        context['vacancy_list']=Vacancy.objects.filter(~Q(slug=self.kwargs['slug']))
        cur_language = translation.get_language()
        context['cur_language'] = cur_language
        context['default_url'] = 1
        context['x'] = self.request.user.id
        context['y'] = vacancy_obj.id


        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        # When the form is submitted, it will enter here
        # self.object = None
        self.form = self.get_form(self.form_class)

        if self.form.is_valid():
            self.form.save()
            # Here ou may consider creating a new instance of form_class(),
            # so that the form will come clean.

        # Whether the form validates or not, the view will be rendered by get()
        return self.get(request, *args, **kwargs)

templates/vacancy/application_page.html
{% extends "base.html" %}
{% load filename_tags %}
{% load i18n %}

{% block title %} {% trans 'My Application' %} {% endblock %}

<script>
var fileExtentionRange = '.zip .rar .tar .pdf .doc .docx .xls .xlsx .ppt .pptx';
        var MAX_SIZE = 30; // MB

        $(document).on('change', '.btn-file :file', function() {
            var input = $(this);

            if (navigator.appVersion.indexOf("MSIE") != -1) { // IE
                var label = input.val();

                input.trigger('fileselect', [ 1, label, 0 ]);
            } else {
                var label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                var numFiles = input.get(0).files ? input.get(0).files.length : 1;
                var size = input.get(0).files[0].size;

                input.trigger('fileselect', [ numFiles, label, size ]);
            }
        });

        $('.btn-file :file').on('fileselect', function(event, numFiles, label, size) {
            $('#resultfile').attr('name', 'resultfile'); // allow upload.

            var postfix = label.substr(label.lastIndexOf('.'));
             $('#_resultfile').val(label);
            if (fileExtentionRange.indexOf(postfix.toLowerCase()) > -1) {
                if (size > 1024 * 1024 * MAX_SIZE ) {
                	alert('max size：<strong>' + MAX_SIZE + '</strong> MB.');

                    $('#resultfile').removeAttr('name'); // cancel upload file.

                } else {
                    $('#_resultfile').val(label);
                }
            } else {
                alert('file type：<br/> <strong>' + fileExtentionRange + '</strong>');

                $('#resultfile').removeAttr('name'); // cancel upload file.
            }
        });
</script>

{% block content %}
    {% trans 'Job Applications' %}
<h2>{% trans 'Requirements' %}</h2>
    <div class="requirements">
<div class="left"><span>{% trans 'Location' %}::</span> {{ vacancy.vacancy.location }}</div>
<div class="right"><span>{% trans 'Education' %}::</span> {{ vacancy.vacancy.education }}</div>
    <br>
<div class="left"><span>{% trans 'Salary description' %}::</span> {{ vacancy.vacancy.salary_description }}</div>
<div class="right"><span>{% trans 'Experience' %}:: </span> {{ vacancy.vacancy.experience }}</div>
    <br>
    </div>
{#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Tasks~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#}
<h2>{% trans 'Tasks' %}</h2>

<table class="ui table segment">
    <thead>
            <tr>
                <th class="text-left">{% trans 'Name' %}</th>
                <th class="text-left">{%  trans 'Source File' %}</th>
                <th class="text-left">{%  trans 'Deadline' %}</th>
                <th class="text-left">{%  trans 'Result File' %}</th>
            </tr>
    </thead>
    <tbody>
    {% for task in tasks %}
        <tr>
            <td>{{ task.name }} {{ task.id }}</td>           {# Position #}
            <td><a href="{{ MEDIA_URL }}{{ task.sourcefile }}"> {{ task.sourcefile|sourcefilename }}</a></td>                  {# Date #}
            <td>{{ task.deadline }}</td>               {# Status #}
             {% if  not task.resultfile %}
            <td>
                <form method="POST"  enctype="multipart/form-data">
                {% csrf_token %}
                        <div class="field">
                            <div class="ui action input">
                                <input type="text" id="_resultfile">
                                <label for="resultfile" class="ui icon button btn-file">
                                     <i class="attachment basic icon"></i>
                                     <input type="file" id="resultfile" name="resultfile" style="display:none">
                                </label>
                            </div>
                        </div>
                        <input type="hidden" id="id_id"  name="id" value="{{ task.id }}">
                        <button  class="ui blue button">{% trans 'Submit' %}</button>
                </form>
            </td>
            {% else %}
                <td><a href="{{ MEDIA_URL }}{{ task.resultfile }}"> {{ task.resultfile|resultfilename }}</a></td>               {# Status #}
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>
{#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Online Interview~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#}
<h2>{% trans 'Online Interview' %}</h2>
    <table class="ui table segment">
        <thead>
                <tr>
                    <th class="text-left">{% trans 'Date' %}</th>
                    <th class="text-left">{% trans 'Connection' %}</th>
                    <th class="text-left">{% trans 'Comment' %}</th>
                </tr>
        </thead>
        <tbody>
        {% for interview in interviews %}
            <tr>
                <td>{{ interview.date}}</td>           {# Position #}
                <td>{{ interview.connection }}</td>                  {# Date #}
                <td>{{ interview.comment }}</td>               {# Status #}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  MessaginG  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#}

    <h3 style="margin-top: 45px;"><i class="mail icon" ></i>{% trans 'Messages' %}</h3>
    <div class="ui form segment" style="border-style: none;">
        <form action="{% url 'core:message_form' %}" method="post">
            {% csrf_token %}
                                        <input type="hidden" id="id_userid"  name="userid" value="{{ request.user.id }}">
                        <input type="hidden" id="id_applicationid"  name="applicationid" value="{{ vacancy.id }}">

            <div style="margin-bottom: 5px;" {% if file_form.comment.errors %} class="field error" {% else %} class="field" {% endif %}>
                    {{ form2.message }}
                        <button class="ui blue button right"> {% trans 'send' %}</button>
                </div>
        </form>
    </div>

    {% for object in msg %}
            <div  {% if forloop.first %} class="ui top attached segment"{% elif forloop.last %} class="ui bottom attached segment" {% else %} class="ui attached segment" {% endif %}>
                <h4>{{ object.userid.get_full_name }}:</h4>
                <p style="margin-left: 10px; margin-top: -4px;">{{ object.message }}</p>
            </div>
        {% endfor %}
{% endblock %}

templates/vacancy/vacancy_apply.html
{% extends "base.html" %}
{% load i18n %}

<title>{% block title %} {% trans 'User Registration' %} {% endblock %}</title>

{% block content %}

{#   {% if message_sent %}#}
{#    <p>#}
{#        {% trans 'Activation link is sent your email address. Please confirm your account and then log in' %}#}
{#    {% else %}#}
    {{ userid }}
       <h1>{% trans 'Job Application Form' %}</h1>
       <div class="ui form segment">
            <form autocomplete="off" action="{% url 'core:user_registration'  %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                        <div class="two fields">
                          <div {% if form.first_name.errors %} class="field error" {% else %} class="field" {% endif %}>
                            {{ form.first_name.label_tag }}
                            <input id="id_first_name" maxlength="50" placeholder="{% trans 'First Name' %}" name="first_name" type="text" />
                            {% if form.first_name.errors %}<div class="ui red pointing prompt label transition visible" style="display: inline-block;">{{ form.first_name.errors.0 }}</div>{% endif %}
                          </div>

                          <div {% if form.last_name.errors %} class="field error" {% else %} class="field" {% endif %}>
                            {{ form.last_name.label_tag }}
                            <input id="id_last_name" maxlength="50" placeholder="{% trans 'Last Name' %}" name="last_name" type="text" />
                            {% if form.last_name.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.last_name.errors.0 }}
                                </div>
                            {% endif %}
                          </div>
                        </div>

                        <div {% if form.cv.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.cv.label_tag }}
                          {{ form.cv }}
                          {% if form.cv.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.cv.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                        <div {% if form.vacancy.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.vacancy.label_tag }}
                          {{ form.vacancy }}
                          {% if form.vacancy.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.vacancy.errors.0 }}
                                </div>
                          {% endif %}
                        </div>
                        <div {% if form.userid.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.userid.label_tag }}
                          {{ form.userid }}
                          {% if form.userid.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.userid.errors.0 }}
                                </div>
                          {% endif %}
                        </div>


                        <button class="ui blue button">{% trans 'Submit' %}</button>

            </form>
       </div>
                
{##}
{#    {% endif %}#}

	
{% endblock %}

templates/vacancy/vacancy_detail.html
{% extends 'base.html' %}
{% load   i18n%}
{% block title %} Vacancies {% endblock %}

{% block content %}
    <div class="vacancy-detail">
        <h1>{{ vacancy.name }}</h1>
        <li><field>{% trans 'Location' %} :: </field>{{ vacancy.location }}</li>

        <li><field>{% trans 'Salary Description' %} :: </field>{{ vacancy.salary_description }}</li>
       <li><field>{% trans 'Education' %} :: </field>{{ vacancy.education }}</li>
       <li><field>{% trans 'Experience' %} :: </field>{{ vacancy.experience }}</li>

{#    </div>#}
{#    <div class="vacancy">#} </br>
        <field><h3><li>{% trans 'Job Description ' %}  :: </li></h3></field><p>{{ vacancy.job_description|safe }}</p>
</div>    <div class="vacancy-detail">

        <a href="/{{ cur_language }}/vacancy/"><span>{% trans 'Return to job list' %}</span></a>
</div>
{% endblock %}

                {% block right-bar-partner %}
       <div class="ui form segment">
       <h2>{% trans 'Job Application Form' %}</h2>

       {% if not user.is_authenticated %}
           {% trans 'Please sign in or register to apply for this job' %}
            <div class="buttons">
                <a class="ui green submit button" href="{% url 'core:user_login' %}">{% trans 'sign in' %}</a>
            </div>
        {% else %}

{#            <form autocomplete="off" action="{% url 'vacancy:vacancy_apply'  %}" method="POST" enctype="multipart/form-data">#}
            <form method="POST"  enctype="multipart/form-data">
                {% csrf_token %}

                        <div {% if form.cv.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.cv.label_tag }}
                          {{ form.cv }}
                          {% if form.cv.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.cv.errors.0 }}
                                </div>
                            {% endif %}
                        </div>

                        <div {% if form.message.errors %} class="field error" {% else %} class="field" {% endif %}>
                          {{ form.message.label_tag }}
                          {{ form.message }}
                          {% if form.message.errors %}
                                <div class="ui red pointing prompt label transition visible" style="display: inline-block;">
                                    {{ form.message.errors.0 }}
                                </div>
                          {% endif %}
                        </div>
                        <input type="hidden" id="id_vacancy"  name="vacancy" value={{ vacancy.id }}>
                        <input type="hidden" id="id_userid"  name="userid" value={{ user.id }}>
                        <input type="hidden" id="id_status"  name="status" value="1">

                        <button  class="ui blue button">{% trans 'Submit' %}</button>

            </form>
                    {% endif %}
                           </div>

                <div id="userlinks">
                        <ul class="list">
                                <li class="news"><a>{% trans 'Other Vacancies' %}</a></li>
                                <div class="links-list">
                {% for other_vacancy in vacancy_list%}
                                        <ul class="link">
                                <li class=""><a href="/{{ cur_language }}/vacancy/{{ other_vacancy.slug }}">{{ other_vacancy.name }}</a></li>
                                        </ul>
                                   {% endfor %}
                                </div>
                        </ul>
                    </div>
{% endblock %}