core/urls.py
from django.conf.urls import patterns, url
from core import views
from workspace import views as wp_views


urlpatterns = patterns('',
    url(r'^$', views.index,  name='index'),
    #user actions
    url(r'^user-registration/$', views.user_register,  name='user_registration'),
    url(r'^partner/registration/$', views.partner_register,  name='registration'),
    url(r'^account/login/$',   views.user_login,  name='user_login'),
    url(r'^partner/profile/update/$',   views.profile_update,  name='profile_update'),
    url(r'^partner/profile/$',   views.profile_info,  name='profile_info'),
    url(r'^account/logout/$',   views.user_logout,  name='user_logout'),
    url(r'^account/password/change/$',   views.userPasswordChange,  name='password_change'),

    url(r'^user/application-page/message/$',views.message_form,name='message_form'),

    url(r'^user/application-page/(?P<id>.*?)/$',views.ApplicationPageView.as_view(),name='application_page'),

    url(r'^user/$',views.user_profile,name='user_profile'),


    url(r'^confirm/(?P<activation_key>[-\w]+)/$',   views.user_confirm,  name='user_confirm'),

    #partnership panel
    url(r'^ppanel/$',  wp_views.partnership_panel,  name='partnership_panel'),
    url(r'^ppanel/employee/(?P<id>[-\w]+)/$',  wp_views.employee_info,  name='employee_info'),
    url(r'^ppanel/workspace/view/(?P<id>.*?)/$',  wp_views.workspace_detail,  name='workspace_detail'),
)

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings

from . import views
from news.settings import ARCHIVE_PAGE_SIZE




urlpatterns = patterns('django.views.generic.date_based',
    url(r'^$', #paginate_by must be egual 
        views.ArchiveIndexView.as_view(paginate_by=ARCHIVE_PAGE_SIZE), name='news_archive_index'),

    url(r'^(?P<slug>[-\w]+)/$',
        views.DetailView.as_view(), name='news_detail'),

)

partnership_program/urls.py
from django.conf.urls import patterns, url
from partnership_program import views

from partnership_program.models import ARCHIVE_PAGE_SIZE


urlpatterns = patterns('',
    url(r'^$',
        views.ArchiveIndexView.as_view(paginate_by=ARCHIVE_PAGE_SIZE), name='all'),
    url(r'^(?P<slug>[-\w]+)/$',  views.program_details,  name='details'),
)

universus_partnership/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns



admin.autodiscover() 
urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^partnership-program/', include('partnership_program.urls', namespace='partnership_program')),
    url(r'^vacancy/', include('vacancy.urls', namespace='vacancy')),

    url(r'^', include('core.urls', namespace='core')),
)

# ... the rest of your URLconf goes here ...

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

vacancy/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
# from django.conf import settings
from . import models
from . import views

urlpatterns = patterns('django.views.generic.date_based',

        url(r'^(?P<slug>.*?)/$',views.VacancyDetailView.as_view(), name='vacancy_detail'),

        url(r'^$',views.vacancy_list, name='vacancy_list'),

)

templates/base.html
{% load   i18n%}
{% load core_tags %}

      <link  type="text/css" rel="stylesheet" media="all" href="{{ STATIC_URL }}css/style.css" />
{#     ui semantic    #}
      <link  type="text/css" rel="stylesheet" media="all" href="{{ STATIC_URL }}css/semantic.css" />
      <link  type="text/css" rel="stylesheet" media="all" href="{{ STATIC_URL }}css/basic.icon.css" />


      <link  type="text/css" rel="stylesheet" media="all" href="{{ STATIC_URL }}css/flexslider.css" />

      <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.7.1.min.js" charset="utf-8"></script>
      <script type="text/javascript" src="{{ STATIC_URL }}js/semantic.js" charset="utf-8"></script>
      <script type="text/javascript" src="{{ STATIC_URL }}js/semantic.min.js" charset="utf-8"></script>
      <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
      {% if request.path|check_request_path %}
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.flexslider.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/functions.js" charset="utf-8"></script>
      {% endif %}
      <script type="text/javascript" src="{{ STATIC_URL }}js/DD_belatedPNG-min.js"></script>




<html>
  <head>
    <title>{% block title %}{% trans '3SC universus | Partnership Portal' %}{% endblock %}</title>
    {% block meta %}
    <meta http-equiv="content-type" content="{% block meta.content-type %}text/html;charset=UTF-8{% endblock meta.content-type %}" />
    <meta name="description" content="{% block meta.description %}{% endblock meta.description %}" />
    <meta name="keywords" content="{% block meta.keywords %}{% endblock meta.keywords %}" />
    {% block meta.extra %}{% endblock meta.extra %}
    {% endblock meta %}
    

    {% block head.extra %}
    {% endblock head.extra %}



  </head> 

  
  <body>
  {% block body %}
	<!-- Wrapper -->
	<div id="wrapper">
		<!-- Header -->
		<div id="header">
			<!-- Shell -->
			<div class="shell">
				<div class="left">
					<a href="{% url 'core:index' %}" title="home"><img class="logo" src="{{ STATIC_URL }}css/images/logo2.png" alt="Partnership portal"/></a>

				</div>
				<!-- Navigation -->
				<div id="navigation">
					<ul>
						<li class="first"><a title="Home" href="{% url 'core:index' %}">{% trans 'Home' %}</a></li>
						<li><a title="Partnership Programs" href="{% url 'partnership_program:all' %}">{% trans 'Partnership Programs' %}</a></li>
						<li><a title="Vacancies" href="{% url 'vacancy:vacancy_list' %}">{% trans 'Vacancies' %}</a></li>
						<li><a title="News" href="{% url 'news:news_archive_index' %} ">{% trans 'News' %}</a></li>
{#						<li><a title="Education" href="#">{% trans 'Education' %}</a></li>#}
						<li><a title="Company" href="http://3sc-universus.com/" target="_blank">{% trans 'Company' %}</a></li>
{#						<li><a target="_blank" title="Contact us" href="http://3sc-universus.com/">{% trans 'Contact us' %}</a></li>#}
                        {% block navications %} {% endblock %}
					</ul>
				</div>
				<!-- END Navigation -->
				<div class="cl"></div>
			</div>
			<!-- END Shell -->
		</div>
		<!-- END Header -->
    {% if request.path|check_request_path %}
		<div id="slider-holder">
			<!-- Shell -->
			<div class="shell">
				<!-- Slider -->
				<div class="flexslider">
					<ul class="slides">
                        {% block slide %}
                            <li>
                                <div class="flex-caption">
                                    <p class="first-line">Accounting</p>
                                    <p class="third-line">Service</p>
                                    <p class="second-line">Program</p>
                                    <span>»&nbsp;<a class="view-more" title="View More" href="{% url 'partnership_program:details' 'accounting-partnership' %}">View More</a></span>
                                </div>
                                <img src="{{ STATIC_URL }}css/images/accounting.png"  />
                            </li>
                            <li>
                                <div class="flex-caption">
                                    <p class="first-line">Service</p>
                                    <p class="third-line">Outsourcing</p>
                                    <p class="second-line">Program</p>
                                    <span>»&nbsp;<a class="view-more" title="View More" href="{% url 'partnership_program:details' 'production-partnership' %}">View More</a></span>
                                </div>
                                <img src="{{ STATIC_URL }}css/images/production.png" />
                            </li>
                            <li>
                                <div class="flex-caption">
                                    <p class="first-line">E-commerce</p>
                                    <p class="third-line">Partnership</p>
                                    <p class="second-line">Program</p>
                                    <span>»&nbsp;<a class="view-more" title="View More" href="{% url 'partnership_program:details' 'ecommerce-partnership' %}">View More</a></span>
                                </div>
                                <img src="{{ STATIC_URL }}css/images/e-commerce.png" />
                            </li>
                            <li>
                                <div class="flex-caption">
                                    <p class="first-line">Promotion &</p>
                                    <p class="third-line">Sales</p>
                                    <p class="second-line">Program</p>
                                    <span>»&nbsp;<a class="view-more" title="View More" href="{% url 'partnership_program:details' 'promotion-partnership' %}">View More</a></span>
                                </div>
                                <img src="{{ STATIC_URL }}css/images/promotion.png" />
                            </li>

                        {% endblock slide %}
					</ul>
				</div>
				<!-- END Slider -->
			</div>
		</div>
    {% endif %}


		<!-- Main -->
		<div id="main">
			<div class="shell">


				<!-- Content -->
				<div id="content">
                    {% block content %}
                        {% for program in part_program %}
                            <div {% if forloop.last %} class="post last" {% else %} class="post" {% endif %}>
                                <h2>{% trans program.name  %}</h2>
                                <div class="img-frame">
                                    <div class="top">
                                        <div class="bottom">
                                            <img src="{{ MEDIA_URL }}{{ program.image }}" alt="" style="width: 287; max-height: 190px;"/>
                                        </div>
                                    </div>
                                </div>
                                <p>{{ program.desc|safe|truncatewords:18}}<a href="{% url 'partnership_program:details' program.slug  %}" title="read more" href="#">{%trans 'read more' %}</a></p>
                            </div>
                        {% endfor %}
                        <div class="cl"></div>
                    {% endblock content %}
				</div>
				<!-- END Content -->

            <div id="rightbar">
                {% block right-bar-partner %}

                    <div class="login">
                        {% if not user.is_authenticated %}
                            <i class="lock icon"></i>
                            <p>{% trans 'Welcome to our parnership portal. Please sign in or register to become our partner' %}</p>

                            <div class="buttons">
                                <a class="ui green submit button" href="{% url 'core:user_login' %}">{% trans 'sign in' %}</a>
                            </div>
                        {% else %}
                            <i class="user icon"></i>
                            <p>{% trans 'Welcome ' %}{{ user.get_full_name}}</p>

                            <div class="buttons">
                                <a class="ui green icon button" href="{% url 'core:user_logout' %}">{% trans 'Log out' %}</a>
                                {% if user.partner %}
                                    <a class="ui green icon button" href="{% url 'core:profile_info' %}">{% trans 'Profile info' %}</a>
                                    <a style="margin:-7px 0px 0px 24px; padding: 7px 30px;" class="ui green icon button" href="{% url 'core:partnership_panel' %}">{% trans 'Partnership panel' %}</a>
                                {% else %}
                                    <a class="ui green icon button" href="{% url 'core:profile_info' %}">{% trans 'Profile info' %}</a>
                                    <a style="margin:-7px 0px 0px 24px; padding: 7px 41px;" class="ui green icon button" href="{% url 'core:user_profile' %}">{% trans 'My application' %}</a>
                                {% endif %}

                            </div>
                        {% endif %}
                    </div>
                {% endblock %}
            {% block right-bar %}
                    <div id="userlinks">
                        <ul class="list">
                                <li class="news"><a>{% trans 'Lattest News' %}</a></li>
                                <div class="links-list">
                                    {% for news in user|get_latest_news %}
                                        <ul class="link">
                                            <li class=""><a href="{{ news.get_absolute_url }}">{{ news.title }}</a></li>
                                        </ul>
                                   {% endfor %}
                                </div>
                        </ul>
                    </div>
                    {% endblock right-bar %}
                </div>


 {% comment %} 
                {% if request.path|check_request_path %}
                    <!-- Widgets -->
                    <div class="widgets">
                        {% block widgets %}
                            <div class="col about-us">
                                <h2>{% trans 'Who We Are?' %}</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum congue aliquam tortor, non malesuada arcu laoreet non. Etiam imperdiet, purus eu rutrum convallis, ante sem iaculis enim, ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum congue aliquam tortor, non malesuada arcu laoreet non. Etiam imperdiet, purus eu rutrum convallis, ante sem. Convallis, ante sem iaculis enim, ut. Lorem ipsum do aliquam tortor, non ma.<a title="read more" href="#">read more.</a></p>
                            </div>
                            <div class="col activities">
                                <h2>{% trans 'What We Do?' %}</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum congue aliquam tortor, non malesuada arcu</p>
                                <ul>
                                    <li><a title="Ut" href="#">Ut dapibus risus id odio luctus lacinia.</a></li>
                                    <li><a title="Praesent" href="#">Praesent consectetur metus aliquam lacus commodo ut porttitor lacus facilisis.</a></li>
                                    <li><a title="Nullam" href="#">Nullam porttitor nibh in ante convallis eu molestie sem molestie.</a></li>
                                    <li><a title="Phasellus" href="#">Phasellus tristique pharetra ipsum, nec fermentum est viverra sit amet.</a></li>
                                </ul>
                            </div>
                            <div class="cl"></div>
                        {% endblock widgets %}
                    </div>
                    <!-- END Widgets -->
                {% endif %}
 {% endcomment %} 
			</div>
			<!-- END Shell -->
		</div>
		<!-- END Main -->
		<div id="footer-push"></div>
	</div>
	<!-- END Wrapper -->
	<!-- Footer -->
	<div id="footer">
        {% block footer %}
            <div class="shell">
                <p class="copy">Copyright 2014<span>|</span><a target="_blank" href="http://3sc-universus.com/">3SC-universus</a></p>
                <p id="bottom-nav">
                    <a title="Home" href="{% url 'core:index' %}">{% trans 'Home' %}</a>
                    <span>|</span><a title="Partnership Partnership Programs" href="{% url 'partnership_program:all' %}">{% trans 'Partnership Programs' %}</a>
                    <span>|</span><a title="Vacancies" href="{% url 'vacancy:vacancy_list' %}">{% trans 'Vacancies' %}</a><span>|</span><a title="News" href="{% url 'news:news_archive_index' %} ">{% trans 'News' %}</a>
{#                    <span>|</span><a title="Education" href="#">{% trans 'Education' %}</a><span>|</span>#}
{#                    <span>|</span><a title="Contact us" href="#">{% trans 'Contact us' %}</a>#}
                    <span>|</span><a title="Company"  href="http://3sc-universus.com/">{% trans 'Company' %}</a></p>
                <div class="cl"></div>
            </div>
        {% endblock footer %}
	</div>
	<!-- END Footer -->

  {% endblock body %}
</body>

</html>
